---
- name: deploy voc control server
  become: true
  git:
    repo: 'https://github.com/chaos-bodensee/voc-control-server.git'
    dest: '/root/control-server'
    update: yes

- name: deploy voc control server
  become: true
  git:
    repo: 'https://github.com/chaos-bodensee/voc-control-server.git'
    dest: '/home/{{ item }}/control-server'
    update: yes
  with_items:
    - '{{ accounts }}' 


